version: "3"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: local/twitter-frontend:v0.1.0
    network_mode: host
    ports:
      - 8000:8000
    expose:
      - "8000"
    depends_on:
      - backend-tweets
      - backend-notifications
    environment:
      # Tracing/Event Key
      NEW_RELIC_API_KEY: XYZZZZZZZZZZZZZZZZZZ

      JAEGER_COLLECTOR: http://127.0.0.1:14268/api/traces
      JAEGER_REPORTER_LOG_SPANS: "true"

  backend-tweets:
    build:
      context: backend-tweets
      dockerfile: Dockerfile
    image: local/twitter-backend-tweets:v0.1.0
    network_mode: host
    ports:
      - 8001:8001
    expose:
      - "8001"
    # depends_on:
    #   - backend-tweets-mysql
    environment:
      # Tracing/Event Key
      NEW_RELIC_API_KEY: XYZZZZZZZZZZZZZZZZZZ

      JAEGER_COLLECTOR: http://127.0.0.1:14268/api/traces
      JAEGER_REPORTER_LOG_SPANS: "true"

  # backend-tweets-mysql:
  #   build:
  #     context: backend-tweets/mysql
  #   image: mysql/mysql-server:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: toor
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: toor
  #     MYSQL_DATABASE: tweets
  #   volumes:
  #     - tweets-mysql-data-volume:/var/lib/mysql
  #     - ./my.cnf:/etc/my.cnf
  #   ports:
  #     - 3306:3306

  backend-notifications:
    build:
      context: backend-notifications
      dockerfile: Dockerfile
    image: local/twitter-backend-notifications:v0.1.0
    network_mode: host
    ports:
      - 8002:8002
    expose:
      - "8002"
    # depends_on:
    #   - backend-notifications-mysql
    environment:
      # Tracing/Event Key
      NEW_RELIC_API_KEY: XYZZZZZZZZZZZZZZZZZZ

      JAEGER_COLLECTOR: http://127.0.0.1:14268/api/traces
      JAEGER_REPORTER_LOG_SPANS: "true"

  # backend-notifications-mysql:
  #   build:
  #     context: backend-notifications/mysql
  #   image: mysql/mysql-server:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: toor
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: toor
  #     MYSQL_DATABASE: notifications
  #   volumes:
  #     - notifications-mysql-data-volume:/var/lib/mysql
  #     - ./my.cnf:/etc/my.cnf
  #   ports:
  #     - 3306:3306

  jaeger-all-in-one:
    network_mode: host
    image: jaegertracing/all-in-one:1.20
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      SPAN_STORAGE_TYPE: memory
    command: ["--log-level=debug"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

# volumes:
#   tweets-mysql-data-volume:
#   notifications-mysql-data-volume:
